---
title: "Predicting Activities - Practical Machine Learning Assignment"
author: "Dr. Ali Sajid Imami"
date: "April 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

This document is a report generated as a partial requirement fulfillment for the [Coursera](https://coursera.org) course [Practical Machine Learning](). This course is part of the [Data Science Specialization]() by the prestigious [John's Hopkins University's Bloomberg School of Public Health]().

This report is generated in in R, utilizing the Rmd format for report's markup and R language for all the relevant calculations. The report generation process was considerably eased by RStudio and the associated knitr package.

## Introduction

_Copied from the course assignment page_

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks.

One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. 

More information is available from the website here: http://web.archive.org/web/20161224072740/http:/groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).

